### ISSUE TITLE
Feature Request: Add ability to remove the /ss/ portion of the URL

### ISSUE THREAD

**Issue by GitPuffy** [rbeer/nodebb-plugin-smoothshorts#7]
I would find it advantageous if I could have the `/ss/` portion of the URL removed from the provided link.  **Only from the portion of the URL that the user gets in his copy buffer.  Not necessarily from how your software works on the backside**

Let me attempt to explain what I do
- I have a custom domain just to use with smoothshorts.  It is not associated with my NodeBB forum or domain in anyway except that it is a `Forced domain` in the smoothshorts configuration.
- I have my Nginx configuration set to rewrite all _shortdomain/ss/x_ URLS to my actual domain name (_realforumdomain/ss/x_) **And this works today perfectly!**
- I would like to have the ability that when a user copies a smoothshort link it would only be _shortdomain/x_.  I would then have a Nginx rewrite rule that would turn that URL back into _realforumdomain/ss/x_

Thank you.

**Comment by rbeer** [comment]
Alright, this should do the trick. :smile:

You can pull the `0.3.0-pre` branch to test the feature. Feedback is appreciated. Especially on whether the automatic settings update is safe. Your former 'Forced Domain' setting should show up in the 'URL Format' field (given that the checkbox was checked, otherwise the value is ignored).

**Comment by GitPuffy** [comment]
Your new changes work like a **champ!** Thank you.  I'll keep testing new versions as you put them out.

And yes, my previous `Forced Domain` setting was retained.  It actually contained my short domain the "/ss" path and then ":hash".  

I've since changed it to just my shortdomain/:hash and it works just as I was hoping.

**Comment by rbeer** [comment]
> It actually contained my short domain the "/ss" path and then ":hash".

Yup, that was my plan. Keeping the domain/ss/:hash thing as default and let the admin change it as deemed fit. Thanks for testing! :smiley: :

**Comment by rbeer** [comment]
published in 0.3.0 / 1386a2a
