### ISSUE TITLE
Things to test in 0.3.0-pre?

### ISSUE THREAD

**Issue by GitPuffy** [rbeer/nodebb-plugin-smoothshorts#9]
Aside from the ability to change around the shortlink URL (which is ahhmazing, btw) is there anything else significant that I should see in `0.3.0-pre`?  I am using the Lavender theme, if that matters.

Thank you.

**Comment by rbeer** [comment]
Not yet, no. I am in the midst of figuring out the best way to implement #3.

**Comment by GitPuffy** [comment]
Btw, I had to manually install xxhash to get 0.3.0-pre working.  `npm install xxhash`

I do not know if that is something your package should know about or not.

**Comment by rbeer** [comment]
It should and actually does: [package.json#L9-L11](https://github.com/rbeer/nodebb-plugin-smoothshorts/blob/master/package.json#L9-L11)
`npm install` should have been enough.

The thing is that NPM installs the dependencies implicitly, when you install a package (e.g. `npm install nodebb-plugins-smoothshorts`). NodeBB issues basically the same command when you install plugins from the ACP.
If you, however, clone a repo, you'll have to take that step yourself and do the `npm install`. NPM looks for package.json in the current directory and installs that, if you don't give `install` a package name. :)

**Comment by rbeer** [comment]
@GitPuffy 
[New toy](https://github.com/rbeer/nodebb-plugin-smoothshorts/blob/master/README.md#--copy-button) arrived in `master`. :wink: 

merged/published in 0.3.0 / 1386a2a
